-- CreateTable
CREATE TABLE `system_settings` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `siteName` VARCHAR(191) NOT NULL DEFAULT 'E-commerce Timor-Leste',
    `siteDescription` TEXT NOT NULL DEFAULT ('Online marketplace for Timor-Leste'),
    `contactEmail` VARCHAR(191) NOT NULL DEFAULT 'support@ecommercetimor.com',
    `contactPhone` VARCHAR(191) NOT NULL DEFAULT '+670 1234 5678',
    `address` TEXT NOT NULL DEFAULT ('Dili, Timor-Leste'),
    `currency` VARCHAR(191) NOT NULL DEFAULT 'USD',
    `taxRate` DOUBLE NOT NULL DEFAULT 8,
    `serviceFee` DOUBLE NOT NULL DEFAULT 4.5,
    `maintenanceMode` BOOLEAN NOT NULL DEFAULT false,
    `maintenanceMessage` TEXT NOT NULL DEFAULT ('We are currently under maintenance. Please check back later.'),
    `registrationOpen` BOOLEAN NOT NULL DEFAULT true,
    `sellerVerificationRequired` BOOLEAN NOT NULL DEFAULT true,
    `enableGuestCheckout` BOOLEAN NOT NULL DEFAULT true,
    `enableReviews` BOOLEAN NOT NULL DEFAULT true,
    `requireReviewApproval` BOOLEAN NOT NULL DEFAULT true,
    `maxProductImages` INTEGER NOT NULL DEFAULT 5,
    `enableCOD` BOOLEAN NOT NULL DEFAULT true,
    `enableBankTransfer` BOOLEAN NOT NULL DEFAULT true,
    `minCODOrderAmount` DOUBLE NOT NULL DEFAULT 0,
    `maxCODOrderAmount` DOUBLE NOT NULL DEFAULT 1000,
    `autoConfirmBankTransfer` BOOLEAN NOT NULL DEFAULT false,
    `bankName` VARCHAR(191) NULL,
    `bankAccountName` VARCHAR(191) NULL,
    `bankAccountNumber` VARCHAR(191) NULL,
    `bankIBAN` VARCHAR(191) NULL,
    `bankSWIFT` VARCHAR(191) NULL,
    `bankTransferInstructions` TEXT NULL,
    `smtpHost` VARCHAR(191) NULL,
    `smtpPort` INTEGER NOT NULL DEFAULT 587,
    `smtpUser` VARCHAR(191) NULL,
    `smtpPassword` VARCHAR(191) NULL,
    `smtpSecure` BOOLEAN NOT NULL DEFAULT false,
    `fromEmail` VARCHAR(191) NOT NULL DEFAULT 'noreply@ecommercetimor.com',
    `fromName` VARCHAR(191) NOT NULL DEFAULT 'E-commerce Timor-Leste',
    `sendOrderConfirmation` BOOLEAN NOT NULL DEFAULT true,
    `sendPaymentConfirmation` BOOLEAN NOT NULL DEFAULT true,
    `sendShippingUpdate` BOOLEAN NOT NULL DEFAULT true,
    `sendWelcomeEmail` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
